# Generated by Django 5.1.6 on 2025-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('policy_holder_name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('life', 'Life'), ('health', 'Health'), ('vehicle', 'Vehicle'), ('home', 'Home')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
