# Generated by Django 5.1.6 on 2025-03-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedha', '0003_policy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('home', 'Home Insurance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
