# Generated by Django 5.1.6 on 2025-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedha', '0005_claim_user_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('travel', 'Travel Insurance'), ('rental', 'Rental Insurance'), ('disability', 'Disability Insurance'), ('pet', 'Pet Insurance'), ('business', 'Business Insurance'), ('marine', 'Marine Insurance'), ('property', 'Property Insurance'), ('liability', 'Liability Insurance'), ('critical_illness', 'Critical Illness Insurance'), ('workers_compensation', 'Workers Compensation Insurance'), ('long_term_care', 'Long-Term Care Insurance'), ('identity_theft', 'Identity Theft Insurance'), ('umbrella', 'Umbrella Insurance'), ('flood', 'Flood Insurance'), ('earthquake', 'Earthquake Insurance'), ('car_rental', 'Car Rental Insurance'), ('mobile', 'Mobile Phone Insurance'), ('cyber', 'Cyber Insurance')], max_length=50),
        ),
    ]
