# Generated by Django 5.1.6 on 2025-04-03 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=255)),
                ('policy_holder_name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('travel', 'Travel Insurance'), ('rental', 'Rental Insurance'), ('disability', 'Disability Insurance'), ('pet', 'Pet Insurance'), ('business', 'Business Insurance'), ('marine', 'Marine Insurance'), ('property', 'Property Insurance'), ('liability', 'Liability Insurance'), ('critical_illness', 'Critical Illness Insurance'), ('workers_compensation', 'Workers Compensation Insurance'), ('long_term_care', 'Long-Term Care Insurance'), ('identity_theft', 'Identity Theft Insurance'), ('umbrella', 'Umbrella Insurance'), ('flood', 'Flood Insurance'), ('earthquake', 'Earthquake Insurance'), ('car_rental', 'Car Rental Insurance'), ('mobile', 'Mobile Phone Insurance'), ('cyber', 'Cyber Insurance')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insu_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('claim_reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insu_claims', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insu.policy')),
            ],
        ),
    ]
